//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 03:06:12 PM CET 
//

package hr.incom.common.domain.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import hr.incom.common.domain.model.enums.NacinPlacanja;
import hr.incom.common.domain.model.enums.OznakaSlijednosti;

@Entity
public class Racun extends IncomEntity implements Serializable
{
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	protected Long id;

	@Column
	protected String oib;

	@Column
	protected boolean uSustPdv;

	@Column
	protected String datVrijeme;

	@Enumerated
	protected OznakaSlijednosti oznSlijed;

	@Column
	protected String brOznRac;

	@Column
	protected String oznPosPr;

	@Column
	protected String oznNapUr;

	@OneToMany
	protected List<Porez> pdvPorez;

	@OneToMany
	protected List<Porez> pnpPorez;

	@OneToMany
	protected List<PorezOstalo> ostaliPorez;

	@Column
	protected String iznosOslobPdv;

	@Column
	protected String iznosMarza;

	@Column
	protected String iznosNePodlOpor;

	@OneToMany
	protected List<Naknada> naknade;

	@Column
	protected String iznosUkupno;

	@Enumerated
	protected NacinPlacanja nacinPlac;

	@Column
	protected String oibOper;

	@Column
	protected String zastKod;

	@Column
	protected boolean nakDost;

	@Column
	protected String paragonBrRac;

	@Column
	protected String specNamj;

	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getOib()
	{
		return oib;
	}

	public void setOib(String oib)
	{
		this.oib = oib;
	}

	public boolean isuSustPdv()
	{
		return uSustPdv;
	}

	public void setuSustPdv(boolean uSustPdv)
	{
		this.uSustPdv = uSustPdv;
	}

	public String getDatVrijeme()
	{
		return datVrijeme;
	}

	public void setDatVrijeme(String datVrijeme)
	{
		this.datVrijeme = datVrijeme;
	}

	public OznakaSlijednosti getOznSlijed()
	{
		return oznSlijed;
	}

	public void setOznSlijed(OznakaSlijednosti oznSlijed)
	{
		this.oznSlijed = oznSlijed;
	}

	public String getBrOznRac()
	{
		return brOznRac;
	}

	public void setBrOznRac(String brOznRac)
	{
		this.brOznRac = brOznRac;
	}

	public String getOznPosPr()
	{
		return oznPosPr;
	}

	public void setOznPosPr(String oznPosPr)
	{
		this.oznPosPr = oznPosPr;
	}

	public String getOznNapUr()
	{
		return oznNapUr;
	}

	public void setOznNapUr(String oznNapUr)
	{
		this.oznNapUr = oznNapUr;
	}

	public List<Porez> getPdvPorez()
	{
		return pdvPorez;
	}

	public void setPdvPorez(List<Porez> pdvPorez)
	{
		this.pdvPorez = pdvPorez;
	}

	public List<Porez> getPnpPorez()
	{
		return pnpPorez;
	}

	public void setPnpPorez(List<Porez> pnpPorez)
	{
		this.pnpPorez = pnpPorez;
	}

	public List<PorezOstalo> getOstaliPorez()
	{
		return ostaliPorez;
	}

	public void setOstaliPorez(List<PorezOstalo> ostaliPorez)
	{
		this.ostaliPorez = ostaliPorez;
	}

	public String getIznosOslobPdv()
	{
		return iznosOslobPdv;
	}

	public void setIznosOslobPdv(String iznosOslobPdv)
	{
		this.iznosOslobPdv = iznosOslobPdv;
	}

	public String getIznosMarza()
	{
		return iznosMarza;
	}

	public void setIznosMarza(String iznosMarza)
	{
		this.iznosMarza = iznosMarza;
	}

	public String getIznosNePodlOpor()
	{
		return iznosNePodlOpor;
	}

	public void setIznosNePodlOpor(String iznosNePodlOpor)
	{
		this.iznosNePodlOpor = iznosNePodlOpor;
	}

	public List<Naknada> getNaknade()
	{
		return naknade;
	}

	public void setNaknade(List<Naknada> naknade)
	{
		this.naknade = naknade;
	}

	public String getIznosUkupno()
	{
		return iznosUkupno;
	}

	public void setIznosUkupno(String iznosUkupno)
	{
		this.iznosUkupno = iznosUkupno;
	}

	public NacinPlacanja getNacinPlac()
	{
		return nacinPlac;
	}

	public void setNacinPlac(NacinPlacanja nacinPlac)
	{
		this.nacinPlac = nacinPlac;
	}

	public String getOibOper()
	{
		return oibOper;
	}

	public void setOibOper(String oibOper)
	{
		this.oibOper = oibOper;
	}

	public String getZastKod()
	{
		return zastKod;
	}

	public void setZastKod(String zastKod)
	{
		this.zastKod = zastKod;
	}

	public boolean isNakDost()
	{
		return nakDost;
	}

	public void setNakDost(boolean nakDost)
	{
		this.nakDost = nakDost;
	}

	public String getParagonBrRac()
	{
		return paragonBrRac;
	}

	public void setParagonBrRac(String paragonBrRac)
	{
		this.paragonBrRac = paragonBrRac;
	}

	public String getSpecNamj()
	{
		return specNamj;
	}

	public void setSpecNamj(String specNamj)
	{
		this.specNamj = specNamj;
	}

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((brOznRac == null) ? 0 : brOznRac.hashCode());
		result = prime * result + ((datVrijeme == null) ? 0 : datVrijeme.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((iznosMarza == null) ? 0 : iznosMarza.hashCode());
		result = prime * result + ((iznosNePodlOpor == null) ? 0 : iznosNePodlOpor.hashCode());
		result = prime * result + ((iznosOslobPdv == null) ? 0 : iznosOslobPdv.hashCode());
		result = prime * result + ((iznosUkupno == null) ? 0 : iznosUkupno.hashCode());
		result = prime * result + ((nacinPlac == null) ? 0 : nacinPlac.hashCode());
		result = prime * result + (nakDost ? 1231 : 1237);
		result = prime * result + ((naknade == null) ? 0 : naknade.hashCode());
		result = prime * result + ((oib == null) ? 0 : oib.hashCode());
		result = prime * result + ((oibOper == null) ? 0 : oibOper.hashCode());
		result = prime * result + ((ostaliPorez == null) ? 0 : ostaliPorez.hashCode());
		result = prime * result + ((oznNapUr == null) ? 0 : oznNapUr.hashCode());
		result = prime * result + ((oznPosPr == null) ? 0 : oznPosPr.hashCode());
		result = prime * result + ((oznSlijed == null) ? 0 : oznSlijed.hashCode());
		result = prime * result + ((paragonBrRac == null) ? 0 : paragonBrRac.hashCode());
		result = prime * result + ((pdvPorez == null) ? 0 : pdvPorez.hashCode());
		result = prime * result + ((pnpPorez == null) ? 0 : pnpPorez.hashCode());
		result = prime * result + ((specNamj == null) ? 0 : specNamj.hashCode());
		result = prime * result + (uSustPdv ? 1231 : 1237);
		result = prime * result + ((zastKod == null) ? 0 : zastKod.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		Racun other = (Racun) obj;
		if (brOznRac == null)
		{
			if (other.brOznRac != null)
				return false;
		}
		else if (!brOznRac.equals(other.brOznRac))
			return false;
		if (datVrijeme == null)
		{
			if (other.datVrijeme != null)
				return false;
		}
		else if (!datVrijeme.equals(other.datVrijeme))
			return false;
		if (id == null)
		{
			if (other.id != null)
				return false;
		}
		else if (!id.equals(other.id))
			return false;
		if (iznosMarza == null)
		{
			if (other.iznosMarza != null)
				return false;
		}
		else if (!iznosMarza.equals(other.iznosMarza))
			return false;
		if (iznosNePodlOpor == null)
		{
			if (other.iznosNePodlOpor != null)
				return false;
		}
		else if (!iznosNePodlOpor.equals(other.iznosNePodlOpor))
			return false;
		if (iznosOslobPdv == null)
		{
			if (other.iznosOslobPdv != null)
				return false;
		}
		else if (!iznosOslobPdv.equals(other.iznosOslobPdv))
			return false;
		if (iznosUkupno == null)
		{
			if (other.iznosUkupno != null)
				return false;
		}
		else if (!iznosUkupno.equals(other.iznosUkupno))
			return false;
		if (nacinPlac != other.nacinPlac)
			return false;
		if (nakDost != other.nakDost)
			return false;
		if (naknade == null)
		{
			if (other.naknade != null)
				return false;
		}
		else if (!naknade.equals(other.naknade))
			return false;
		if (oib == null)
		{
			if (other.oib != null)
				return false;
		}
		else if (!oib.equals(other.oib))
			return false;
		if (oibOper == null)
		{
			if (other.oibOper != null)
				return false;
		}
		else if (!oibOper.equals(other.oibOper))
			return false;
		if (ostaliPorez == null)
		{
			if (other.ostaliPorez != null)
				return false;
		}
		else if (!ostaliPorez.equals(other.ostaliPorez))
			return false;
		if (oznNapUr == null)
		{
			if (other.oznNapUr != null)
				return false;
		}
		else if (!oznNapUr.equals(other.oznNapUr))
			return false;
		if (oznPosPr == null)
		{
			if (other.oznPosPr != null)
				return false;
		}
		else if (!oznPosPr.equals(other.oznPosPr))
			return false;
		if (oznSlijed != other.oznSlijed)
			return false;
		if (paragonBrRac == null)
		{
			if (other.paragonBrRac != null)
				return false;
		}
		else if (!paragonBrRac.equals(other.paragonBrRac))
			return false;
		if (pdvPorez == null)
		{
			if (other.pdvPorez != null)
				return false;
		}
		else if (!pdvPorez.equals(other.pdvPorez))
			return false;
		if (pnpPorez == null)
		{
			if (other.pnpPorez != null)
				return false;
		}
		else if (!pnpPorez.equals(other.pnpPorez))
			return false;
		if (specNamj == null)
		{
			if (other.specNamj != null)
				return false;
		}
		else if (!specNamj.equals(other.specNamj))
			return false;
		if (uSustPdv != other.uSustPdv)
			return false;
		if (zastKod == null)
		{
			if (other.zastKod != null)
				return false;
		}
		else if (!zastKod.equals(other.zastKod))
			return false;
		return true;
	}
}
